import revscoring

from revscoring.features import page, parent_revision, revision, user
from revscoring.features.modifiers import log, max

from ..features import diff, revision


reverted = [
#    revscoring.features.diff.longest_repeated_char_added,
#    revscoring.features.diff.longest_token_added,
#    log(revscoring.features.diff.numeric_chars_added + 1),
#    log(revscoring.features.diff.numeric_chars_removed + 1),
#    revscoring.features.diff.proportion_of_chars_added,
#    revscoring.features.diff.proportion_of_chars_removed,
#    revscoring.features.diff.proportion_of_numeric_chars_added,
#    revscoring.features.diff.proportion_of_symbolic_chars_added,
#    revscoring.features.diff.proportion_of_uppercase_chars_added,
#    log(revscoring.features.diff.symbolic_chars_added + 1),
#    log(revscoring.features.diff.symbolic_chars_removed + 1),
#    log(revscoring.features.diff.uppercase_chars_added + 1),
#    log(revscoring.features.diff.uppercase_chars_removed + 1),
#    revscoring.features.diff.bytes_changed + 1,
#    revscoring.featuresdiff.bytes_changed_ratio,
#    page.is_content_namespace,
#    parent_revision.was_same_user,
#    log(user.age + 1),
    diff.number_added_sitelinks,
    diff.number_removed_sitelinks,
    diff.number_changed_sitelinks,
    diff.number_added_labels,
    diff.number_removed_labels,
    diff.number_changed_labels,
    diff.number_added_descriptions,
    diff.number_removed_descriptions,
    diff.number_changed_descriptions,
    diff.number_added_aliases,
    diff.number_removed_aliases,
    diff.number_added_claims,
    diff.number_removed_claims,
    diff.number_changed_claims,
    diff.number_changed_identifiers,
    diff.en_label_touched,
    diff.number_added_sources,
    diff.number_removed_sources,
    diff.number_added_qualifiers,
    diff.number_removed_qualifiers,
    diff.number_added_badges,
    diff.number_removed_badges,
#    diff.mean_distance_descriptions,
#    diff.mean_distance_labels,
    diff.proportion_of_qid_added,
    diff.proportion_of_langauge_added,
    diff.proportion_of_links_added,
    diff.P21_changed,
    diff.P27_changed,
    diff.P54_changed,
    diff.P569_changed,
    diff.P18_changed,
    diff.P109_changed,
    diff.P373_changed,
    diff.P856_changed,
    revision.number_claims,
    revision.number_aliases,
    revision.number_sources,
    revision.number_qualifiers,
    revision.number_badges,
    revision.number_labels,
    revision.number_sitelinks,
    revision.number_descriptions,
    revision.is_human,
    revision.is_blp,
    user.is_bot,
    user.is_anon,
]
